global:
  slack_api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'

route:
  group_by: ['alertname', 'severity']

  receiver: 'slack'

receivers:
- name: default-receiver
  webhook_configs:
  - url: 'http://localhost:9094/api/v1/alerts'

