route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

# inhibit_rules:
#   - source_match:
#       alertname: MyApp5-Absent
#     target_match:
#       alertname: ^(MyApp[1-4])-Absent$
#     equal: true

inhibit_rules:
  - source_match:
      alertname: 'MyApp5-Absent'
    target_match:
      alertname: '.*' # Match all alertnames

receivers:
  - name: 'local'
    webhook_configs:
      - url: 'http://127.0.0.1:9093/api/v2/alerts'
