route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'hooksite'

inhibit_rules:
  - source_matchers:
      - alertname = "MyApp5-Absent"
      - instance = "10.10.11"
    target_matchers:
      - alertname = "MyApp5-Absent"
      - job =~ "monitoring_postgres_prd|bull-libjobs|kafka-dlq-exporter"
    
receivers:
  - name: 'hooksite'
    webhook_configs:
      - url: 'https://webhook.site/4392e784-9e26-49fe-b709-52b9582380e6'

