route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'hooksite'

inhibit_rules:
  - source_match:
      alertname: "MyApp5-Absent"
    target_matchers:
      - alertname != "MyApp5-Absent"
    
receivers:
  - name: 'hooksite'
    webhook_configs:
      - url: 'https://webhook.site/41783e71-1097-439d-95bb-c2601e508147'
