route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'hooksite'

inhibit_rules:
  - source_match:
      alertname: "MyApp5-Absent"
    target_matchers:
      - alertname != "MyApp5-Absent"
    
receivers:
  - name: 'hooksite'
    webhook_configs:
      - url: 'https://webhook.site/1a127120-1b58-4ed0-b7a9-ec7851fd32b6'
