version: '3'
services:
  my-app1:
    image: my-app:latest
    ports:
      - "5001:5000"
    networks:
      - monitoring
  my-app2:
    image: my-app:latest
    ports:
      - "5002:5000"
    networks:
      - monitoring
  my-app3:
    image: my-app:latest
    ports:
      - "5003:5000"
    networks:
      - monitoring
  my-app4:
    image: my-app:latest
    ports:
      - "5004:5000"
    networks:
      - monitoring
  my-app5:
    image: my-app:latest
    ports:
      - "5005:5000"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules/alerts.rules.yml:/etc/prometheus/alerts.rules.yml
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager_templates:/etc/alertmanager/templates
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
