global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-app1'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['my-app1:5000']
  - job_name: 'my-app2'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['my-app2:5000']
  - job_name: 'my-app3'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['my-app3:5000']
  - job_name: 'my-app4'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['my-app4:5000']
  - job_name: 'my-app5'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['my-app5:5000']

rule_files:
  - /etc/prometheus/alerts.rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
