apiVersion: v1
kind: Service
metadata:
  name: argocd-service
spec:
  selector:
    app: argocd
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081
