apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  labels:
    app: argocd
spec:
  replicas: 1  # You can adjust the number of replicas as needed.
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:v2.0.1  # Use the desired ArgoCD version.
        ports:
        - containerPort: 8080
        - containerPort: 8081